modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Realistic%20Bees"
logoFile="icon.png"

[[mods]]
modId="realisticbees"
version="4.4"
displayName="Realistic Bees"
displayURL="https://serilum.com/mod/realistic-bees"
authors="Serilum"
description='''Bees are tiny, more bee spawns and bigger space in beehives.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.realisticbees]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.realisticbees]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"