modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Realistic%20Bees"
logoFile="icon.png"

[[mods]]
modId="realisticbees"
version="3.8"
displayName="Realistic Bees"
displayURL="https://serilum.com/mod/realistic-bees"
authors="Rick South"
description='''Bees are tiny, more bee spawns and bigger space in beehives.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.realisticbees]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.realisticbees]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"